dist: xenial
language: c
compiler:
  - clang
  - gcc
services:
  - docker
before_install:
  - sudo apt-get install -y cppcheck clang-format
  - make fmt && git diff --exit-code
  - make lint
script:
  - docker build -t mishegos_ci .
