./src/worker/bfd/bfd.so
./src/worker/capstone/capstone.so
./src/worker/dynamorio/dynamorio.so
./src/worker/fadec/fadec.so
./src/worker/udis86/udis86.so
./src/worker/xed/xed.so
./src/worker/zydis/zydis.so
./src/worker/bddisasm/bddisasm.so
./src/worker/iced/iced.so
./src/worker/yaxpeax-x86/libyaxpeax_x86_mishegos.so
