#!/usr/bin/env ruby
# frozen_string_literal: true

# filter-all-failure: remove all cohorts in which each worker failed

require "json"

warn "[+] pass: filter-all-failure"

count = 0
$stdin.each_line do |line|
  result = JSON.parse line, symbolize_names: true

  if result[:outputs].all? { |o| o[:status][:name] == "failure" }
    count += 1
    next
  end

  $stdout.puts result.to_json
end

warn "[+] pass: filter-all-failure done: #{count} filtered"
