#!/usr/bin/env ruby
# frozen_string_literal: true

# filter-all-failure: remove all cohorts in which each worker failed

require "json"

STDERR.puts "[+] pass: filter-all-failure"

count = 0
STDIN.each_line do |line|
  result = JSON.parse line, symbolize_names: true

  if result[:outputs].all? { |o| o[:status][:name] == "S_FAILURE" }
    count += 1
    next
  end

  STDOUT.puts result.to_json
end

STDERR.puts "[+] pass: filter-all-failure done: #{count} filtered"
