#!/usr/bin/env python3

import json
import os
import sys
from cohorts import Cohorts

verbose = os.getenv("V")


def main():
    cohorts = Cohorts.from_io(sys.stdin.buffer)

    for cohort in cohorts.cohorts:
        outputs = []
        for idx, output in enumerate(cohort.outputs, start=1):
            outputs.append(
                {
                    "status": {
                        "value": output.status.value,
                        "name": output.status.name.upper(),
                    },
                    "ndecoded": output.ndecoded,
                    "workerno": output.workerno,
                    "worker_so": output.worker_so,
                    "len": output.len,
                    "result": output.result,
                }
            )

            if verbose and idx % 1000 == 0:
                print(
                    f"[+] Processed {idx} cohorts ({idx * cohort.nworkers} outputs)",
                    file=sys.stderr,
                )

        cohort = {
            "nworkers": cohort.nworkers,
            "input": cohort.input,
            "outputs": outputs,
        }

        print(json.dumps(cohort), file=sys.stdout)


if __name__ == "__main__":
    main()
